name: Sync Admin Branch

on:
  push:
    branches:
      - main

jobs:
  sync_admin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout admin branch
        run: git checkout admin

      - name: Rebase admin onto main
        run: git rebase origin/main

      - name: Push changes to admin
        run: |
          git push --force-with-lease origin admin
